version: "3.4"

services:
  backend:
    build: ./backend
    command: yarn watch-server
    ports:
      - 3001:3001

  frontend:
    build: ./frontend
    command: yarn start
    depends_on:
      - backend
    ports:
      - 4200:4200

